### ISSUE TITLE
Spec error running `lein figwheel`

### ISSUE THREAD

**Issue by kernelp4nic** [tiensonqin/exponent-cljs-template#38] opened 2017-08-28 12:16 UTC
I tried to run `lein figwheel` and got an error getting dependencies: 

```clojure
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.11/figwheel-sidecar-0.5.11.jar from clojars
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/refer-clojure did not conform to spec:
In: [2] val: (quote :as) fails at: [:args :exclude :op :spec] predicate: #{:exclude}
In: [2 1] val: :as fails at: [:args :exclude :op :quoted-spec :spec] predicate: #{:exclude}
In: [2] val: (quote :as) fails at: [:args :only :op :spec] predicate: #{:only}
In: [2 1] val: :as fails at: [:args :only :op :quoted-spec :spec] predicate: #{:only}
In: [2] val: (quote :as) fails at: [:args :rename :op :spec] predicate: #{:rename}
In: [2 1] val: :as fails at: [:args :rename :op :quoted-spec :spec] predicate: #{:rename}
:clojure.spec.alpha/args  ((quote :exclude) (quote [reduce into merge map take partition partition-by]) (quote :as) (quote core))
 {:clojure.spec.alpha/problems ({:path [:args :exclude :op :spec], :pred #{:exclude}, :val (quote :as), :via [], :in [2]} {:path [:args :exclude :op :quoted-spec :spec], :pred #{:exclude}, :val :as, :via [], :in [2 1]} {:path [:args :only :op :spec], :pred #{:only}, :val (quote :as), :via [], :in [2]} {:path [:args :only :op :quoted-spec :spec], :pred #{:only}, :val :as, :via [], :in [2 1]} {:path [:args :rename :op :spec], :pred #{:rename}, :val (quote :as), :via [], :in [2]} {:path [:args :rename :op :quoted-spec :spec], :pred #{:rename}, :val :as, :via [], :in [2 1]}), :clojure.spec.alpha/args ((quote :exclude) (quote [reduce into merge map take partition partition-by]) (quote :as) (quote core))}, compiling:(clojure/core/async.clj:9:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6925)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
	at clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2277)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6918)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6916)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
```

It seems like this is a problem with core.async? maybe a version missmatch?

My steps where:
- `lein new expo your-project +om`
- `cd your-project`
- `lein figwheel`

**Comment by seantempesta** [comment] 2017-08-30 12:16
I just tried to reproduce your error and couldn't.  Are you sure you're using the latest version of the template?

**Comment by seantempesta** [comment] 2017-09-12 19:05
Closing because I couldn't reproduce the problem.  Please reopen if you can share an example of the bug.

**Closed as completed by seantempesta** 2017-09-12 19:05 UTC
