### ISSUE TITLE
problem using @expo/vector-icons

### ISSUE THREAD

**Issue by andfadeev** [tiensonqin/exponent-cljs-template#55] opened 2018-03-05 18:51 UTC
Hi! Need help to figure out problem using `@expo/vector-icons` in cljs project.

In react native this works:
```
import { MaterialIcons } from '@expo/vector-icons';
```
```
<MaterialIcons name="search" size={50}/>
```

But in cljs:

```
(def VectorIcons (js/require "@expo/vector-icons"))
(def MaterialIcons (r/adapt-react-class (.-MaterialIcons VectorIcons)))
```
```
[MaterialIcons {:name "search"}]
```
Results in (top left corner) on device with expo client or emulator: 
<img width="171" alt="screen_shot_2018-03-04_at_12 31 16" src="https://user-images.githubusercontent.com/2952149/36993288-798d0ff8-20be-11e8-95fe-af978515e142.png">

I guess, i'm missing something(

I start expo with `exp start -a -c .` in project root

**Comment by seantempesta** [comment] 2018-03-06 03:45
Yeah, I can reproduce this.  I spent a couple of hours on this and I still don't know why it's not working.  I think it has something to do with pre-loading fonts?

https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html

**Comment by carocad** [comment] 2018-03-20 22:57
This has also happened to me but using NativeBase UI framework which depends on those vector 
icons. 

In my case I found out that it only happened if I used a specific version of that ui framework. After downgrading my deps to an older one the problem disappeared ... no idea why 🤔 

hope it helps

**Comment by seantempesta** [comment] 2018-04-07 06:50
Okay, well if we can't repro it I'm going to close the issue.  Glad the problem went away for you!

**Closed as completed by seantempesta** 2018-04-07 06:50 UTC

**Comment by robert-johansson** [comment] 2018-04-08 09:16
@carocad @andfadeev I get the same error, and couldn't downgrade further than NativeBase 2.3.1 without getting other errors. Is there any possibility that you could provide me with a working example of the latest expo-cljs template + NativeBase that actually works? That would be awesome.

**Comment by carocad** [comment] 2018-04-08 09:34
@robert-johansson I think this is the version of expo-cljs that I am using: 175776bb6a827668a7d518e729946ee007bbf86d

Quite outdated but it still works :)

Here are my dependencies, maybe those would help
```
"dependencies": {
    "create-react-class": "15.6.0",
    "expo": "^21.0.0",
    "native-base": "^2.3.3",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-navigation": "^1.0.0-beta.19"
  },
  "devDependencies": {
    "exp": "46.0.3"
}
```

PS: if you are getting a problem with NativeBase saying that it cannot find `Feather.js` that is a bug on their side but it gets even more complicated to solve since both NativeBase and Expo require react-native-icons

**Comment by andfadeev** [comment] 2018-04-08 09:58
Still getting the same result, no icon is shown. Generated project with latest version of template (no extra deps).

**Comment by carocad** [comment] 2018-04-08 10:28
@andfadeev I remember that once when I was using re-natal I had a similar problem and a fresh install of the expo `mobile` app seemed to solve the issue. Not sure why though. You can try something like

`exp install:android`

However I am not even sure that this is a template problem since the problem is quite common even in js apps 😞 

https://github.com/GeekyAnts/NativeBase/issues/138
https://github.com/oblador/react-native-vector-icons/issues/661
http://discuss.nativebase.io/t/not-show-icon-in-react-native-vector-icon/123/7

**Comment by robert-johansson** [comment] 2018-04-08 15:01
Thanks for suggestions @carocad . There are no differences between using the exact config you use, and using the newest Expo+NativeBase etc.

On Android simulator, it starts up with crossed icons, instead of icons. On iOS simulator, it complains on missing Ionicons: "Unrecognized font family 'ionicons'".

Are you including Ionicons in your Clojure code, or somewhere else? I explored doing it, but no success.

This code generates crossed-out icons on Android simulator. Could you see any obvious errors, or something else related to Ionicons?

https://gist.github.com/robert-johansson/68f6e6f04890679c1c5cb9b194675480

Thanks for any suggestions.

PS:
Pictures from Android and iOS simulators follow.

<img width="729" alt="screen shot 2018-04-08 at 16 46 13" src="https://user-images.githubusercontent.com/8457281/38469023-b7a2edb2-3b4e-11e8-8043-6fa6b981c14c.png">

<img width="559" alt="screen shot 2018-04-08 at 16 46 06" src="https://user-images.githubusercontent.com/8457281/38469027-bc96d68a-3b4e-11e8-8329-88c9377467e0.png">

**Comment by carocad** [comment] 2018-04-08 16:10
@robert-johansson I dont see any obvious errors however I would recommend you to try these

- load the fonts with Expo: https://docs.expo.io/versions/latest/guides/using-custom-fonts
- get your iOS app into a clean state, enable Chrome Debugging and make it stop on `catched exceptions`.
  - then introduce the code that creates the problem and follow it back to your `node-modules`.
  - Check that the `react-native-vector-icons`  from native-base is not interfeering with the one from `expo`
- try contacting nativeBase directly. I doubt that this is a cljs template problem so you would probably have more luck over there ;)

Hope it helps

**Comment by robert-johansson** [comment] 2018-04-08 16:22
@carocad Thanks! Will try these things!

**Comment by pm4r** [comment] 2018-04-24 11:51
Has anyone got it working?

I struggled a couple of hours with various options, like loading font as described in https://docs.expo.io/versions/latest/guides/using-custom-fonts, delaying initial view, using createIconSet on ttf and glyphs json copied into assets dir - nothing worked. On Android 7 icons looks like chinese characters, on 4.5 they doesn't appear, and on iPhone I got exception "Unrecognized font family.." on app loading. Tested on latest expo client connected over wifi.

It can be easily reproduced by running `lein new expo ..` and just adding sth like this:

```
(def VectorIcons (js/require "@expo/vector-icons"))
(def icon-fa (r/adapt-react-class (.-FontAwesome VectorIcons)))
```
and somewhere in view:
`[icon-fa {:name "bars" :style {:font-size 20 :color "red"}}]`

Also I had to upgrade to expo 26 because of some exception with fetch during startup.

**Comment by carocad** [comment] 2018-04-24 12:31
@pm4r this is probably related to #59

**Comment by pm4r** [comment] 2018-04-24 13:41
Thanks dude, it works :)

I made exactly same changes as in #59 in figwheel-bridge.js and core.cljs (reagent version) - fonts work now as expected.

**Comment by seantempesta** [comment] 2018-04-24 16:02
Great!  I just integrated the pull request.  Thank you everyone for getting to the bottom of this!
