### ISSUE TITLE
Images not visualized in prod build

### ISSUE THREAD

**Issue by frankiesardo** [tiensonqin/exponent-cljs-template#23] opened 2017-04-04 14:05 UTC
## Issue

Once you build with `lein prod-build` and publish to an expo url, the app once downloaded does not display any images at all.

## Steps to reproduce:

This happens on a fresh project

`lein new exponent sample && npm install && lein prod-build && exp publish`

**Comment by ducky427** [comment] 2017-04-08 19:06
I can also confirm this.

**Comment by ducky427** [comment] 2017-04-11 09:24
This may be due to the way Exponent deals with Assets. See [doc](https://docs.expo.io/versions/v15.0.0/guides/assets.html)

**Comment by tiensonqin** [comment] 2017-04-25 16:19
@ducky427 @frankiesardo 
Sorry for the late response, I haven't followed both RN and Exponent recently, any update on this?

**Comment by seantempesta** [comment] 2017-05-17 12:12
@ducky427: Checking in on this.  Are you still having this problem?  My assets seem to be coming through when they are published.  I believe you need to have explicit 

```clojure
(js/require "asset-path/asset.jpg") 
```
statements or else Expo won't pick them up.

**Comment by ducky427** [comment] 2017-05-30 15:00
@seantempesta, I just tried and I am still getting the same issue.

**Comment by seantempesta** [comment] 2017-08-01 04:14
@ducky427: Maybe you're using an old version of the `exp` command?  Maybe try publishing it with the XDE app instead?  I noticed expo switched to a separate asset build step when publishing.

**Comment by ducky427** [comment] 2017-08-16 10:33
@seantempesta, I tried the same thing in the latest version and I can't reproduce the issue anymore.

Thanks!

**Comment by seantempesta** [comment] 2017-08-16 11:10
Fixed in v0.19

**Closed as completed by seantempesta** 2017-08-16 11:10 UTC
