### ISSUE TITLE
Figwheel not working

### ISSUE THREAD

**Issue by johnjelinek** [tiensonqin/exponent-cljs-template#49] opened 2017-12-31 03:15 UTC
Any change I make requires a reload:
![what_happened](https://user-images.githubusercontent.com/873610/34458842-88385bde-eda6-11e7-9bf5-81aab0860ecc.gif)

**Comment by johnjelinek** [comment] 2017-12-31 03:17
Both Live Reload and Hot Reloading are disabled ^

**Comment by johnjelinek** [comment] 2017-12-31 03:25
The red screen appears anytime exp shows this message in stdout:
```
[exp] Figwheel: notified of file changes
```

**Comment by seantempesta** [comment] 2017-12-31 06:30
Hmm, I'm not seeing this.  I just created a new reagent template and it seems to be reloading fine.  

![live-reload-working](https://user-images.githubusercontent.com/726276/34459847-8ed2f3c6-edc1-11e7-9abf-6d4575c34861.gif)

**Comment by johnjelinek** [comment] 2017-12-31 15:18
I'm not sure if this matters, but I'm on JDK9 and the server with figwheel is remote (cloud instance) and my emulator is local.

**Comment by seantempesta** [comment] 2017-12-31 15:58
Is Figwheel connecting? I forgot to include instructions that you need to
do an `adb reverse tcp:3449 tcp:3449` for android to even get figwheel to
connect.

**Comment by johnjelinek** [comment] 2017-12-31 16:11
it must be connecting if the repl shows up in `lein figwheel` and I see messages like `[exp] Figwheel: notified of file changes` in `exp start`, right?

**Comment by seantempesta** [comment] 2017-12-31 16:13
Yeah, if you can type in the repl then everything is working.  I wonder if this is `om` related?  Can you reproduce the problem with the reagent template?

**Comment by johnjelinek** [comment] 2017-12-31 16:20
I had other issues with the reagent template, but I can give it another
shot.

**Comment by johnjelinek** [comment] 2017-12-31 17:05
<img width="644" alt="react_native_version_mismatch" src="https://user-images.githubusercontent.com/873610/34463232-58b286cc-ee1a-11e7-82d4-14ce50744089.png">

This is what I get with the `reagent` template.

**Comment by johnjelinek** [comment] 2017-12-31 17:08
Also, if I run `adb reverse tcp:3449 tcp:3449`, it returns: `error: closed` -- the reagent template wasn't able to load the repl.

**Comment by johnjelinek** [comment] 2017-12-31 18:15
after playing with the `package.json` for the reagent template, I was able to get it to load, but when I make changes, there are still problems, specifically when changing the `@greeting`:
![what_happened](https://user-images.githubusercontent.com/873610/34463526-41803e18-ee24-11e7-87fb-3029fe3abf8c.gif)

This is the message in `expo`:
```
[exp] re-frame: overwriting, :event, handler for:,  {
  "_hash": -653540063,
  "cljs$lang$protocol_mask$partition0$": 2153775105,
  "cljs$lang$protocol_mask$partition1$": 4096,
  "fqn": "set-greeting",
  "name": "set-greeting",
  "ns": null,
}
* js/figwheel-bridge.js:117:14 in <unknown>
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 10 more stack frames from framework internals
```

**Comment by seantempesta** [comment] 2017-12-31 18:43
The re-frame warning is normal and happens anytime you reload the handlers.  And the greeting itself shouldn't change until you reload the entire app (as the greeting is stored in the app-db atom).  

If instead of changing the `db.cljs` file, you do this in the repl:

```clojure
(re-frame.core/dispatch [:set-greeting "Hello Native World!"])
```
Does the text update without a reload?

**Comment by johnjelinek** [comment] 2017-12-31 19:39
that updates without a reload -- I'll have to figure out how that works. So, is it not recommended to use the `om` template then?

**Comment by seantempesta** [comment] 2017-12-31 19:52
I wouldn't say that.  I'm not familiar with om-next, so I haven't spent a lot of time testing the template to make sure it's setup properly.  I'll take a look and see if I can reproduce it on my end.

**Comment by seantempesta** [comment] 2018-02-15 07:16
Closing this as I couldn't reproduce the error.  Please feel free to re-open if the issue can be re-created.

**Closed as completed** 2018-02-15 07:15 UTC
